<a href="https://colab.research.google.com/github/EtinosaE/NYPD-Shooting-Incident/blob/main/pickles2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!tar zxvf ./sample_data/pickles.tgz

./._fX_test.p
./fX_test.p
./._fX_train.p
./fX_train.p
./._fy_test.p
./fy_test.p
./._fy_train.p
./fy_train.p


In [3]:
# pickles
# Train and Test datasets stored as pytthon pickles
import pickle
fX_train = open('fX_train.p','rb')
X_train = pickle.load(fX_train)
fX_train.close()
fy_train = open('fy_train.p', 'rb')
y_train = pickle.load(fy_train)
fy_train.close()
fX_test = open('fX_test.p', 'rb')
X_test = pickle.load(fX_test)
fX_test.close()
fy_test = open('fy_test.p','rb')
y_test = pickle.load(fy_test)
fy_test.close()

In [4]:
import tensorflow as tf
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(128, activation='sigmoid', input_dim=608))
for i in range(200):
  model.add(tf.keras.layers.Dense(16, activation='sigmoid'))
  #model.add(Dropout(rate=0.1))

  # the target vector consist of 32 fields containing either a 0 or a 1
  model.add(tf.keras.layers.Dense(32, activation='sigmoid'))

In [6]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['binary_accuracy'])
print(model.summary())
model.fit(X_train, y_train, epochs=20, batch_size=100)
model.evaluate(X_test, y_test)
predicted = model.predict(X_test)
print(predicted)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               77952     
                                                                 
 dense_1 (Dense)             (None, 16)                2064      
                                                                 
 dense_2 (Dense)             (None, 32)                544       
                                                                 
 dense_3 (Dense)             (None, 16)                528       
                                                                 
 dense_4 (Dense)             (None, 32)                544       
                                                                 
 dense_5 (Dense)             (None, 16)                528       
                                                                 
 dense_6 (Dense)             (None, 32)                5

In [7]:
print(predicted)

[[0.4528207  0.45971575 0.48868808 ... 0.49132413 0.49587306 0.49221638]
 [0.4528207  0.45971575 0.48868808 ... 0.49132413 0.49587306 0.49221638]
 [0.4528207  0.45971575 0.48868808 ... 0.49132413 0.49587306 0.49221638]
 ...
 [0.4528207  0.45971575 0.48868808 ... 0.49132413 0.49587306 0.49221638]
 [0.4528207  0.45971575 0.48868808 ... 0.49132413 0.49587306 0.49221638]
 [0.4528207  0.45971575 0.48868808 ... 0.49132413 0.49587306 0.49221638]]
